version: "3"

services:
  api:
    container_name: auth-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - AWS_COGNITO_REGION=${AWS_COGNITO_REGION}
      - AWS_COGNITO_CLIENT_ID=${AWS_COGNITO_CLIENT_ID}
      - AWS_API_GATEWAY_ID=${AWS_API_GATEWAY_ID}
      - AWS_API_GATEWAY_RESOURCE_ID=${AWS_API_GATEWAY_RESOURCE_ID}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./:/home/app:rw
