service: visor-auth-lmb-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ${env:AWS_COGNITO_REGION}

  # This is necessary to use only api to multi-resource
  apiGateway:
    restApiId: 143gm9rzn3
    restApiRootResourceId: a71yvg

functions:
  functionName:
    AuthLmb:
    # Environment variables need to be in OS
    environment:
      AWS_COGNITO_REGION: ${env:AWS_COGNITO_REGION}
      AWS_COGNITO_CLIENT_ID: ${env:AWS_COGNITO_CLIENT_ID}
    handler: index.handler
    events:
      # Accept any path that is added to the service
      - http:
          path: /auth/{proxy+}
          method: ANY

plugins:
  # plus to serverless work offile
  - serverless-offline

custom:
  # This is necessary because the docker to use this host
  serverless-offline:
    host: 0.0.0.0
